runtime: nodejs20

env_variables:
  NODE_ENV: 'production'
  DB_HOST: '/cloudsql/mqi-interns-467405:us-central1:product-management-db'
  DB_USER: 'sigma'
  DB_PASSWORD: 'sigma'
  DB_NAME: 'product_management_system'
  SESSION_SECRET: 'pms-production-secret-key-2025-change-me-in-production'

beta_settings:
  cloud_sql_instances: mqi-interns-467405:us-central1:product-management-db

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always # Redirects all HTTP traffic to HTTPS
