runtime: nodejs20
service: default

env_variables:
  NODE_ENV: 'production'
  DB_HOST: '/cloudsql/mqi-ims:us-central1:product-management-db'
  DB_USER: 'sigma'
  DB_PASSWORD: 'sigma'
  DB_NAME: 'product_management_system'
  SESSION_SECRET: 'pms-production-secret-key-2025-change-me-in-production'
  EMAIL_USER: 'priyanshu17ks.edu@gmail.com'
  EMAIL_PASS: 'bztn fcvu zaig dztn'
  ADMIN_EMAIL: 'priyanshu17ks@gmail.com'

beta_settings:
  cloud_sql_instances: mqi-ims:us-central1:product-management-db

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always