runtime: nodejs20

env_variables:
  NODE_ENV: 'production'
  DB_HOST: '/cloudsql/mqi-ims:us-central1:product-management-db'
  DB_USER: 'sigma'
  DB_NAME: 'product_management_system'
  # Secure secrets from Secret Manager
  DB_PASSWORD: 'projects/mqi-ims/secrets/db-password/versions/latest'
  SESSION_SECRET: 'projects/mqi-ims/secrets/session-secret/versions/latest'

beta_settings:
  cloud_sql_instances: mqi-ims:us-central1:product-management-db

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always